[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace STM32G071C8Rx with your chip as listed in `probe-rs chip list`
runner = "probe-rs run --chip stm32g431cbUx"
rustflags = [
  "-C", "linker=flip-link", # <- add this
  # (..)
]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "debug"
